#include "neck/feedback_server.h"

#include "neck/neck_motion.h"

extern "C" {
#include "transmit.h"
}

#include <cerrno>
#include <chrono>
#include <cmath>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <utility>

#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/un.h>
#include <unistd.h>

namespace {

constexpr double kMaximumRateHz = 1000.0;

double unixNowSeconds() {
    return std::chrono::duration<double>(
        std::chrono::system_clock::now().time_since_epoch()).count();
}

std::string formatNumber(double value) {
    if (!std::isfinite(value)) {
        return "0";
    }
    std::ostringstream output;
    output << std::setprecision(9) << value;
    return output.str();
}

// Unix timestamps are ~1.8e9; nine significant digits would only give 1 s
// resolution, so timestamp needs its own fixed-point formatter.
std::string formatTimestamp(double value) {
    if (!std::isfinite(value)) {
        return "0";
    }
    std::ostringstream output;
    output << std::fixed << std::setprecision(6) << value;
    return output.str();
}

// Reasons are limited to a fixed vocabulary generated by this file, but the
// provider is injectable, so keep the JSON string safe anyway.
std::string safeReason(const std::string& reason) {
    std::string result;
    result.reserve(reason.size());
    for (char character : reason) {
        const bool allowed =
            (character >= 'a' && character <= 'z') ||
            (character >= 'A' && character <= 'Z') ||
            (character >= '0' && character <= '9') ||
            character == '_' || character == '-';
        result.push_back(allowed ? character : '_');
    }
    if (result.empty()) {
        result = "invalid";
    }
    return result;
}

std::string formatSample(const FeedbackSample& sample) {
    std::ostringstream output;
    output << "{\"type\":\"motor_state\",\"version\":1,\"timestamp\":"
           << formatTimestamp(sample.timestamp_sec)
           << ",\"valid\":" << (sample.valid ? "true" : "false")
           << ",\"motion_executing\":" << (sample.motion_executing ? "true" : "false");
    if (sample.valid) {
        output << ",\"unit\":\"degree\",\"order\":[\"pitch\",\"roll\",\"yaw\"]"
               << ",\"head_rpy\":["
               << formatNumber(sample.pose_deg.pitch) << ","
               << formatNumber(sample.pose_deg.roll) << ","
               << formatNumber(sample.pose_deg.yaw) << "]"
               << ",\"motor_angles\":["
               << formatNumber(sample.motor_angles_deg[0]) << ","
               << formatNumber(sample.motor_angles_deg[1]) << ","
               << formatNumber(sample.motor_angles_deg[2]) << "]"
               << ",\"sequence\":["
               << sample.sequence[0] << ","
               << sample.sequence[1] << ","
               << sample.sequence[2] << "]";
    } else {
        output << ",\"reason\":\"" << safeReason(sample.reason) << "\"";
    }
    output << "}\n";
    return output.str();
}

}  // namespace

FeedbackProvider makeNeckFeedbackProvider(const NeckConfig& config) {
    return [config](double timestamp_sec) {
        FeedbackSample sample;
        sample.timestamp_sec = timestamp_sec;
        sample.motion_executing = isTrajectoryExecuting();

        int passages[3];
        int motor_ids[3];
        for (std::size_t index = 0; index < config.motors.size(); ++index) {
            passages[index] = config.motors[index].passage;
            motor_ids[index] = config.motors[index].id;
        }

        double angles_deg[3];
        std::uint64_t sequences[3];
        if (!NeckFeedbackRead(config.slave_id, passages, motor_ids,
                              angles_deg, sequences)) {
            sample.reason = "feedback_unavailable";
            return sample;
        }

        const MotorAngles motors{angles_deg[0], angles_deg[1], angles_deg[2]};
        NeckPose pose;
        if (forwardKinematics(motors, config, pose) !=
            NeckKinematicsStatus::Ok) {
            sample.reason = "kinematics_failed";
            return sample;
        }

        sample.valid = true;
        sample.reason = "ok";
        sample.pose_deg = pose;
        for (std::size_t index = 0; index < 3; ++index) {
            sample.motor_angles_deg[index] = angles_deg[index];
            sample.sequence[index] = sequences[index];
        }
        return sample;
    };
}

FeedbackServer::FeedbackServer(std::string socket_path, double rate_hz,
                               FeedbackProvider provider)
    : socket_path_(std::move(socket_path)),
      rate_hz_(rate_hz),
      provider_(std::move(provider)) {}

FeedbackServer::~FeedbackServer() {
    stop();
}

bool FeedbackServer::removeStaleSocket(std::string& error_message) {
    struct stat file_status {};
    if (lstat(socket_path_.c_str(), &file_status) != 0) {
        if (errno == ENOENT) {
            return true;
        }
        error_message = "cannot inspect existing feedback socket path: " +
                        std::string(std::strerror(errno));
        return false;
    }
    if (!S_ISSOCK(file_status.st_mode)) {
        error_message = "refusing to remove non-socket path: " + socket_path_;
        return false;
    }
    if (unlink(socket_path_.c_str()) != 0) {
        error_message = "cannot remove stale feedback socket: " +
                        std::string(std::strerror(errno));
        return false;
    }
    return true;
}

void FeedbackServer::removeOwnedSocket() {
    struct stat file_status {};
    if (lstat(socket_path_.c_str(), &file_status) == 0 &&
        S_ISSOCK(file_status.st_mode)) {
        unlink(socket_path_.c_str());
    }
}

bool FeedbackServer::start(std::string& error_message) {
    error_message.clear();
    if (running_.load()) {
        error_message = "feedback server is already running";
        return false;
    }
    if (!provider_) {
        error_message = "feedback pose provider must be set";
        return false;
    }
    if (socket_path_.empty()) {
        error_message = "feedback socket path must not be empty";
        return false;
    }
    if (!std::isfinite(rate_hz_) || rate_hz_ <= 0.0 ||
        rate_hz_ > kMaximumRateHz) {
        error_message = "feedback rate must be finite and in (0, 1000] Hz";
        return false;
    }

    sockaddr_un address {};
    address.sun_family = AF_UNIX;
    if (socket_path_.size() >= sizeof(address.sun_path)) {
        error_message = "feedback socket path is too long: " + socket_path_;
        return false;
    }
    if (!removeStaleSocket(error_message)) {
        return false;
    }

    listen_fd_ = socket(AF_UNIX, SOCK_STREAM, 0);
    if (listen_fd_ < 0) {
        error_message = "feedback socket() failed: " +
                        std::string(std::strerror(errno));
        return false;
    }
    std::memcpy(address.sun_path, socket_path_.c_str(), socket_path_.size() + 1);
    if (bind(listen_fd_, reinterpret_cast<sockaddr*>(&address),
             sizeof(address)) != 0) {
        error_message = "feedback bind() failed: " +
                        std::string(std::strerror(errno));
        close(listen_fd_);
        listen_fd_ = -1;
        removeOwnedSocket();
        return false;
    }
    if (listen(listen_fd_, 8) != 0) {
        error_message = "feedback listen() failed: " +
                        std::string(std::strerror(errno));
        close(listen_fd_);
        listen_fd_ = -1;
        removeOwnedSocket();
        return false;
    }
    if (chmod(socket_path_.c_str(), 0666) != 0) {
        error_message = "feedback chmod() failed: " +
                        std::string(std::strerror(errno));
        close(listen_fd_);
        listen_fd_ = -1;
        removeOwnedSocket();
        return false;
    }

    running_ = true;
    try {
        accept_thread_ = std::thread(&FeedbackServer::acceptLoop, this);
        publish_thread_ = std::thread(&FeedbackServer::publishLoop, this);
    } catch (const std::exception& exception) {
        running_ = false;
        close(listen_fd_);
        listen_fd_ = -1;
        removeOwnedSocket();
        error_message = std::string("cannot start feedback threads: ") +
                        exception.what();
        return false;
    }

    std::cout << "[FeedbackServer] listening on " << socket_path_ << " ("
              << rate_hz_ << " Hz)\n";
    return true;
}

void FeedbackServer::stop() {
    if (!running_.exchange(false)) {
        if (accept_thread_.joinable()) {
            accept_thread_.join();
        }
        if (publish_thread_.joinable()) {
            publish_thread_.join();
        }
        removeOwnedSocket();
        return;
    }

    // Wake a blocking accept(). The accept loop observes running_ == false and
    // closes this connection without adding it as a client.
    const int wake_fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (wake_fd >= 0) {
        sockaddr_un address {};
        address.sun_family = AF_UNIX;
        if (socket_path_.size() < sizeof(address.sun_path)) {
            std::memcpy(address.sun_path, socket_path_.c_str(),
                        socket_path_.size() + 1);
            connect(wake_fd, reinterpret_cast<sockaddr*>(&address),
                    sizeof(address));
        }
        close(wake_fd);
    }

    if (accept_thread_.joinable()) {
        accept_thread_.join();
    }
    if (publish_thread_.joinable()) {
        publish_thread_.join();
    }

    {
        std::lock_guard<std::mutex> lock(clients_mutex_);
        for (int client : clients_) {
            close(client);
        }
        clients_.clear();
    }

    if (listen_fd_ >= 0) {
        close(listen_fd_);
        listen_fd_ = -1;
    }
    removeOwnedSocket();
}

bool FeedbackServer::isRunning() const {
    return running_.load();
}

const std::string& FeedbackServer::socketPath() const {
    return socket_path_;
}

void FeedbackServer::acceptLoop() {
    while (running_.load()) {
        const int client_fd = accept(listen_fd_, nullptr, nullptr);
        if (client_fd < 0) {
            if (errno == EINTR) {
                continue;
            }
            if (running_.load()) {
                std::cerr << "[FeedbackServer] accept() failed: "
                          << std::strerror(errno) << "\n";
            }
            break;
        }
        if (!running_.load()) {
            close(client_fd);
            break;
        }

        // A stalled client must not block the publisher: drop it when the
        // socket send buffer stays full for 200 ms.
        struct timeval send_timeout {};
        send_timeout.tv_usec = 200000;
        setsockopt(client_fd, SOL_SOCKET, SO_SNDTIMEO,
                   &send_timeout, sizeof(send_timeout));

        std::size_t client_count = 0;
        {
            std::lock_guard<std::mutex> lock(clients_mutex_);
            clients_.push_back(client_fd);
            client_count = clients_.size();
        }
        std::cout << "[FeedbackServer] client connected (" << client_count
                  << " total)\n";
    }
}

void FeedbackServer::publishLoop() {
    const auto period = std::chrono::duration_cast<
        std::chrono::steady_clock::duration>(
        std::chrono::duration<double>(1.0 / rate_hz_));
    auto next = std::chrono::steady_clock::now() + period;

    while (running_.load()) {
        const double timestamp_sec = unixNowSeconds();
        FeedbackSample sample = provider_(timestamp_sec);
        if (!std::isfinite(sample.timestamp_sec)) {
            sample.timestamp_sec = timestamp_sec;
        }
        broadcast(formatSample(sample));

        std::this_thread::sleep_until(next);
        next += period;
        const auto now = std::chrono::steady_clock::now();
        if (next < now) {
            // Do not try to catch up after a long stall; resync the deadline.
            next = now + period;
        }
    }
}

void FeedbackServer::broadcast(const std::string& line) {
    std::lock_guard<std::mutex> lock(clients_mutex_);
    for (std::size_t index = 0; index < clients_.size();) {
        const int client_fd = clients_[index];
        const ssize_t sent = send(client_fd, line.data(), line.size(),
                                  MSG_NOSIGNAL);
        if (sent == static_cast<ssize_t>(line.size())) {
            ++index;
            continue;
        }
        close(client_fd);
        clients_.erase(clients_.begin() + index);
        std::cout << "[FeedbackServer] client disconnected (" << clients_.size()
                  << " remaining)\n";
    }
}
